### PR TITLE
[BAD-318] Hadoop File Output/Input steps fail to output to HDFS with Hadoop-snappy compression

### PR DESCRIPTION
**Pull request by stepanovdg**
* Removed necessary for old shims pentaho-snappy artifact.

### CODE REVIEW

**Comment by stepanovdg** [comment]
@mattyb149 Could you please take a look?

**Comment by stepanovdg** [comment]
@mattyb149 Could you please take a look?

**Comment by mattyb149** [comment]
Looks good but why the 5.4 branch? I didn't see a BACKLOG or SP case around 5.4, I would've thought this would go into master (or both)

**Comment by mattyb149** [comment]
ok I see #258 and merged it. How is the 5.4 backport being tracked in Jira?

**Comment by stepanovdg** [comment]
Ok, I wasn`t sure where it should be fixed. It was found in 5.4. So created a pull-request for this branch. 
Also https://github.com/pentaho/pentaho-hadoop-shims/pull/260 I have realized that Mapr410 was missed from the list.

**Comment by mattyb149** [comment]
All PRs should be issued against master, if the Triage team selects it for backport, you will have an associated SP case for the older branch to issue a new PR against.

I need to close this in the meantime, but thank you for including the link in the original case. If they deem it necessary for backport, we can reopen and merge at that time.

**Pull request closed without merging**
