### PR TITLE
[BACKLOG-8801]: Create and Compile EMR 4.6 SHIM against Pentaho 6.1

### PR DESCRIPTION
**Pull request by TatsianaKasiankova**
The new EMR 4.6 shim reworked according to the new upcoming dependency management changes:
1)All third party and test dependencies use transitive="false";
2)Pentaho Dependencies uses the property keys from the global version.properties for their versions;

### CODE REVIEW

**Comment by TatsianaKasiankova** [comment]
@dkincade Hi, please review the PR.

**Comment by dkincade** [comment]
@TatsianaKasiankova do you get these errors locally when you try to use the approved repositories?

**Comment by TatsianaKasiankova** [comment]
@dkincade No, I do not.

**Comment by TatsianaKasiankova** [comment]
I've built the new EMR46 for 6.1 on our test job:
http://ci.pentaho.com/job/pentaho-hadoop-shims-stepanovdg-fork1/155/ - everything is Ok

**Comment by lucboudreau** [comment]
@TatsianaKasiankova Pleas emake sure to clear all of your local caches (ivy and maven, ``~/.ivy2/cache`` and ``~/.m2/repository``) and run the exact command as above, including the repository parameter.

```
ant -Dpentaho.resolve.repo=http://ivy-nexus.pentaho.org/content/groups/approved -Dtestreports.dir=bin/reports/unit-test -f build.xml clean-all resolve jacoco && ant -Dpentaho.resolve.repo=http://ivy-nexus.pentaho.org/content/groups/approved -Dtestreports.dir=bin/reports/integration-test -f build.xml jacoco-integration checkstyle publish-local
```

That should do the trick.

**Comment by lucboudreau** [comment]
@buildguy Please take a look at this pull request. It looks like the version of ASM included as a dependency of Jacoco does not contain an expected class. Version error?

**Comment by dkincade** [comment]
Based on conversation with @lucboudreau this is a library failure generating unit test results after all unit tests pass. Including this pull request.

**Pull request merged**
