### PR TITLE
[BACKLOG-3253] - HBase Input fails if Filter condition is specified

### PR DESCRIPTION
**Pull request by stepanovdg**
* Added unit test
* Removed unnecessary override
* Changed classname separator for inner class

### CODE REVIEW

**Comment by stepanovdg** [comment]
@mattyb149 Could you please take a look?

**Comment by kcruzada** [comment]
@mattyb149 can you process this pull request?

**Comment by kcruzada** [comment]
@mattyb149 can you process this pull request?

**Comment by mattyb149** [comment]
Why is this a problem with just the EMR32 shim? Judging by the fix, it should affect all shims...

**Comment by stepanovdg** [comment]
EMR shim is using old hbase version, but initial shim was copied from the later one. So fix for emr part is in removing two overriden methods. By the way during the unit tests writing was found that other methods which return classnames are written in wrong format (internal classes must use other separator than the dot). So this part was also was fixed.

**Comment by mattyb149** [comment]
Don't we have other shims (like hadoop-20) that use the old HBase version? If so, does it need to be fixed as well? If this fix also works for hadoop-20, doesn't that mean this is currently a problem for that shim?

**Comment by stepanovdg** [comment]
By default common shim contains classnames for the old version. So if new hbase version is used these methods are overriden in certain shim. So this override in EMR shim was redundant. About the changes in common shim - in previous way it couldn`t work due to java reflection specification. So seems that code was never work.

**Comment by kcruzada** [comment]
@mattyb149 Code Freeze is tomorrow.  What needs to happen to move this forward?

**Pull request merged**
