### PR TITLE
[BAD-509]: Create and Compile CDH 5.7 SHIM against Pentaho 6.1.x

### PR DESCRIPTION
**Pull request by TatsianaKasiankova**
This is an initial version of the new CDH 5.7 (CE version). The component process is tracked in BAD-511 issue and processed like for all other shims.

### CODE REVIEW

**Comment by TatsianaKasiankova** [comment]
@brosander Hi, please review the PR.

**Comment by TatsianaKasiankova** [comment]
@hudak Hi, please review the PR.

**Comment by brosander** [comment]
@TatsianaKasiankova have new component requests been filed for the new jars?

**Comment by TatsianaKasiankova** [comment]
The component process is tracked in BAD-511 issue and processed like for all other shims. It is in process.

**Pull request merged**
