### PR TITLE
[BACKLOG-8540] -  Create the MapR 5.1 Shim (against Pentaho 7.0)

### PR DESCRIPTION
**Pull request by alexzhk**
The Oozie issue remains unresolved.

### CODE REVIEW

**Comment by alexzhk** [comment]
Could you @dkincade @hudak please review my changes?

**Comment by hudak** [comment]
@alexzhk Are you waiting to add this shim to build.modules.list ?

**Comment by dkincade** [comment]
@alexzhk - Yes, this should be added to the build module list (and MapR401 should be removed from that list)

**Comment by alexzhk** [comment]
Added mapr510 to the build module list and removed mapr401 from that list

**Comment by lucboudreau** [comment]
Close, but that was not what I expected. Let me make some more changes in Wingman and try again.

**Pull request merged**
