### PR TITLE
Backport of [BACKLOG-34725] Update CDP DC Shim version to 7.1.4 dependencies

### PR DESCRIPTION
**Pull request by renjith-nem**
Master Branch PR: 
https://github.com/pentaho/pentaho-hadoop-shims/pull/1197

### CODE REVIEW

**Comment by lucboudreau** [comment]
Wrong branch. Should be "9.1"

**Review by lucboudreau — APPROVED** [review]

**Review by ssamora — APPROVED** [review]

**Comment by lucboudreau** [comment]
@ssamora You, sir, have read our minds. :)

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 5m 13s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl shims/cdpdc71/driver
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by ssamora** [comment]
@lucboudreau i was "walking by" :)

**Pull request merged**
