### PR TITLE
[TAP-908] - Add parquet input component to process multiple files at once

### PR DESCRIPTION
**Pull request by rmansoor**

### CODE REVIEW

**Comment by rmansoor** [comment]
@jgminder please review

**Comment by buildguy** [comment]
### :warning: Build finished in 12m 16s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl common-fragment-V1,shim-api
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 3 test(s) failed:

<details><summary><b>org.pentaho.hadoop.shim.common.ConfigurationProxyV2Test.checkConfigsInConfigurationAddedHiveSiteXml</b> (click to expand)</summary><p>

```
Central Log Store is not initialized!!!
```

</p></details>

<details><summary><b>org.pentaho.hadoop.shim.common.ConfigurationProxyV2Test.checkConfigsInConfigurationAddedHbaseSiteXml</b> (click to expand)</summary><p>

```
Central Log Store is not initialized!!!
```

</p></details>

<details><summary><b>org.pentaho.hadoop.shim.common.ConfigurationProxyV2Test.checkConfigsInConfigurationAddedHDFSSiteXml</b> (click to expand)</summary><p>

```
Central Log Store is not initialized!!!
```

</p></details>

  
Tests run: **924**, Failures: **3**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/big-data-hadoop-shims/job/PR-1153/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 12m 27s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl common-fragment-V1,shim-api
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 3 test(s) failed:

<details><summary><b>org.pentaho.hadoop.shim.common.ConfigurationProxyV2Test.checkConfigsInConfigurationAddedHiveSiteXml</b> (click to expand)</summary><p>

```
Central Log Store is not initialized!!!
```

</p></details>

<details><summary><b>org.pentaho.hadoop.shim.common.ConfigurationProxyV2Test.checkConfigsInConfigurationAddedHbaseSiteXml</b> (click to expand)</summary><p>

```
Central Log Store is not initialized!!!
```

</p></details>

<details><summary><b>org.pentaho.hadoop.shim.common.ConfigurationProxyV2Test.checkConfigsInConfigurationAddedHDFSSiteXml</b> (click to expand)</summary><p>

```
Central Log Store is not initialized!!!
```

</p></details>

  
Tests run: **924**, Failures: **3**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/big-data-hadoop-shims/job/PR-1153/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 12m 30s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl common-fragment-V1,shim-api
```
---
:ok_hand: All tests passed!
 
Tests run: **924**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/big-data-hadoop-shims/job/PR-1153/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 11m 53s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl common-fragment-V1,shim-api
```
---
:ok_hand: All tests passed!
 
Tests run: **924**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/big-data-hadoop-shims/job/PR-1153/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 10m 58s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl common-fragment-V1,shim-api
```
---
:ok_hand: All tests passed!
 
Tests run: **924**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/big-data-hadoop-shims/job/PR-1153/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
