### PR TITLE
[BAD-261] - PentahoTableInputFormat does not work on secured Hadoop cluster

### PR DESCRIPTION
**Pull request by stepanovdg**
* Added RequiredCredentialsToken which works at client side and allows to obtain required tokens w/out changes internally in shim`s abstraction layer.

### CODE REVIEW

**Comment by stepanovdg** [comment]
related to https://github.com/pentaho/pentaho-big-data-ee/pull/102

**Comment by stepanovdg** [comment]
@brosander Could you please take a look and merge or make some comments?

**Comment by brosander** [comment]
Hey Stepanov, I'm on PTO today.  If it's urgent, please reach out to womprats or r2d2.

On Feb 8, 2016 8:13 AM, Stepanov Dmitriy <notifications@github.com> wrote:

@brosander<https://github.com/brosander> Could you please take a look and merge or make some comments?

-

**Comment by stepanovdg** [comment]
Hi Bryan, 
Could you please take a look now (pull-requests are updated). 
Or anybody else.
Thank you,
Dzmitry

**Comment by brosander** [comment]
@stepanovdg have you tested the hsp changes?

**Comment by stepanovdg** [comment]
No, I didn`t have access to hsp cluster. I did only unit tests at all latest shims (http://ci.pentaho.com/job/pentaho-hadoop-shims-stepanovdg-fork/97/) and functionality tests at hdp23secured cluster. 
When I did refactoring before I didn`t notice that shim. And now making changes in new-common (affected all new shims) I also was need to make the same changes in hsp. So decided to refactor also this one. Also I wasn`t able to refactor or find secured version of this shim.

**Comment by stepanovdg** [comment]
@brosander  Any updates?

**Comment by brosander** [comment]
On travel headed back to Orlando today.  Should be able to take a look then.  @hudak may be able to check it out sooner.

On Feb 12, 2016 5:17 AM, Dmitriy Stepanov <notifications@github.com> wrote:

@brosander<https://github.com/brosander> Any updates?

-

**Comment by stepanovdg** [comment]
Great, thank you ))

**Comment by brosander** [comment]
@stepanovdg I agree that it makes more sense to pull hsp into common but we've already called it good to ship, I'm going to start an email thread to discuss

**Comment by stepanovdg** [comment]
@brosander  
Bryan, I have separated changes  from BAD-261 (doubled common changes for the hsp) and hsp refactoring. 
https://github.com/pentaho/pentaho-hadoop-shims/pull/332 - BAD-261
https://github.com/pentaho/pentaho-hadoop-shims/pull/333 - HSP
So HSP pull-request could be merged after verification and in another time.

**Comment by stepanovdg** [comment]
@brosander @hudak - Could you please look again? http://jira.pentaho.com/browse/BAD-261

**Comment by brosander** [comment]
@stepanovdg please rebase against master

**Comment by stepanovdg** [comment]
@brosander Rebased.

**Pull request merged**
