### PR TITLE
[PDI-10400] - Overriding date to get NULL into query with no quotes arou...

### PR DESCRIPTION
**Pull request by brosander**
...nd it

### CODE REVIEW

**Comment by kolinus** [comment]
should it be merged to 5.3 as well ?

**Comment by dkincade** [comment]
Yes it should be in 5.3 also

Thanks,
David

On Jan 21, 2015, at 4:08 AM, Kanstantsin Karneliuk <notifications@github.com<mailto:notifications@github.com>> wrote:


should it be merged to 5.3 as well ?

-

**Comment by brosander** [comment]
That's my bad, 185 was supposed to be 5.3, user error...

**Comment by brosander** [comment]
Looks like I beat the branch actually
https://github.com/pentaho/pentaho-hadoop-shims/commits/5.3

**Pull request merged**
