### PR TITLE
[BACKLOG-8539] - Create the MapR 5.1 Shim (against Pentaho 6.1)

### PR DESCRIPTION
**Pull request by alexzhk**
The Oozie issue remains unresolved.
PMR Hadoop and Yarn-Kettle jobs issue [[BACKLOG-9528]](http://jira.pentaho.com/browse/BACKLOG-9528) was fixed and merged into master branch only (pull request - https://github.com/pentaho/pentaho-hadoop-shims/pull/378)

### CODE REVIEW

**Comment by alexzhk** [comment]
ould you @dkincade @hudak please review my changes?

**Comment by dkincade** [comment]
This has a missing dependency: org.apache.pig#pig;0.15.0-mapr-1603!pig.jar

**Comment by alexzhk** [comment]
MapR 5.1 shim needs pig-0.15.0-mapr-1603-h2.jar (with h2-classifier, http://jira.pentaho.com/browse/COMP-3305). I couldn`t find this artifact in the pentaho approved repository. It is still in the private-3rd-party-candidate-release repository.

**Comment by alexzhk** [comment]
Wingman failed to build the shim because of the absent artifacts (org.apache.hadoop components version 2.7.0-mapr-1602, maprfs) in the Pentaho approved repository.

These artifacts need only to build the shim on Wingman and they do not ship with the product. 
As now Wingman needs all artifacts to build the shim  to be in the approved repository I created 
sub-task  [[BACKLOG-9882](http://jira.pentaho.com/browse/BACKLOG-9882)] for [[BACKLOG-8538] (http://jira.pentaho.com/browse/BACKLOG-8538)]  and appropriate jira cases [[COMP-3387](http://jira.pentaho.com/browse/COMP-3387)] - [[COMP-3396](http://jira.pentaho.com/browse/COMP-3396)] to build the shim

**Pull request merged**
