### PR TITLE
[TEST] - pentaho-hadoop-shims continuous problem

### PR DESCRIPTION
**Pull request by stepanovdg**
- To fix CI job running through project root with continuous target

### CODE REVIEW

**Comment by kolinus** [comment]
@mattyb149 , Matt could you please review that?

**Comment by mattyb149** [comment]
The source artifacts should be fully qualified like the "real" artifacts, with the additional classified of "sources". Also I don't think we need a tgz anymore, but if that was copied from subfloor that's ok.

**Comment by stepanovdg** [comment]
This change only affects properties to used depending on module. So each module will receive correct src.dir . The behavior is the same as was before. Inherited from subfloor.xml

**Comment by mattyb149** [comment]
Sorry I misread the Ant command thinking those were the artifact names, when they are actually Ant target names, my bad.

**Pull request merged**
