### PR TITLE
[BACKLOG-8747]: Create and Compile EMR 4.6 SHIM against Pentaho 7.0 (…

### PR DESCRIPTION
**Pull request by TatsianaKasiankova**
…master)

The new EMR 4.6 shim.

### CODE REVIEW

**Comment by TatsianaKasiankova** [comment]
@dkincade , please review the PR.
This is the new EMR 4.6 shim.
For new dependencies/components for EMR 4.6 sim there have been submitted component requests  in http://jira.pentaho.com/browse/BACKLOG-8531

**Comment by dkincade** [comment]
We will need to wait for the artifacts to show up in the approved repository before processing this pull request.

**Comment by dkincade** [comment]
The head build failure from wingman was indeed caused by the top-level folder having a build.xml and not producing a classes folder.
`Tue Jun 14 12:50:06 EDT 2016 - stdout - base: BUILD FAILED
Tue Jun 14 12:50:06 EDT 2016 - stdout - base: /home/buildguy/project/build-res/subfloor.xml:1571: destination directory "/home/buildguy/project/bin/classes" does not exist or is not a directory`

However the head failure appears to be caused by an inability to write a unit test report file:
`Tue Jun 14 12:50:23 EDT 2016 - stdout - head:     [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.902 sec
Tue Jun 14 12:50:23 EDT 2016 - stdout - head:     [junit] Exception in thread "main" Unable to write log file
Tue Jun 14 12:50:23 EDT 2016 - stdout - head:     [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.XMLJUnitResultFormatter.endTestSuite(XMLJUnitResultFormatter.java:199)
Tue Jun 14 12:50:23 EDT 2016 - stdout - head:     [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.fireEndTestSuite(JUnitTestRunner.java:843)
Tue Jun 14 12:50:23 EDT 2016 - stdout - head:     [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:578)
Tue Jun 14 12:50:23 EDT 2016 - stdout - head:     [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1182)
Tue Jun 14 12:50:23 EDT 2016 - stdout - head:     [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1033)
Tue Jun 14 12:50:23 EDT 2016 - stdout - head:     [junit] Caused by: java.io.FileNotFoundException: /home/buildguy/project/emr41/bin/reports/unit-test/xml/TEST-org.pentaho.hadoop.shim.common.delegating.DelegatingHBaseConnectionTest.xml (No such file or directory)`

**Comment by TatsianaKasiankova** [comment]
I'll send the new PR with re-worked EMR4.6 according the new upcoming dependency management changes (BACKLOG-8884).

**Pull request closed without merging**
