### PR TITLE
[BAD-215] Add Support for the Simba Driver

### PR DESCRIPTION
**Pull request by stepanovdg**
Also https://github.com/pentaho/pentaho-hadoop-shims/pull/262 - should be merged in any case just as fixes master branch unit tests.

### CODE REVIEW

**Comment by stepanovdg** [comment]
After  https://github.com/pentaho/big-data-plugin/pull/425 and https://github.com/pentaho/pentaho-big-data-ee/pull/79 should be merged.

**Comment by stepanovdg** [comment]
This pull-request with changes from https://github.com/pentaho/pentaho-hadoop-shims/pull/262 was tested at CI http://ci.pentaho.com/job/pentaho-hadoop-shims-test-fork/21/ . Sucessfully with no failures.

**Comment by stepanovdg** [comment]
@mattyb149 Could you please take a look?

**Comment by dkincade** [comment]
At this point, we will not be adding support for the Simba driver. If we deem it important in the future, we will reopen this pull request.

**Pull request closed without merging**
