### PR TITLE
BACKLOG-34593 mapr61 shim

### PR DESCRIPTION
**Pull request by kodehash**

### CODE REVIEW

**Review by lucboudreau — APPROVED** [review]

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2d 4h 47m 10s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
shims,shims/mapr61,shims/mapr61/driver,shims/mapr61/kar,shims/mapr61/pmr
```
---
:ok_hand: All tests passed!
 
Tests run: **30**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/big-data-hadoop-shims/job/PR-1171/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by kodehash** [comment]
Closing this as we have a another PR against the master branch

**Comment by kodehash** [comment]
Reopening this PR as we will support Mapr61 on 9.1 now.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 12m 17s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
shims,shims/mapr61,shims/mapr61/driver,shims/mapr61/kar,shims/mapr61/pmr
```
---
:ok_hand: All tests passed!
 
Tests run: **30**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/big-data-hadoop-shims/job/PR-1171/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
