### PR TITLE
[BACKLOG-8540] - Create the MapR 5.1 Shim (against Pentaho 7.0) - add oss-license.filename property

### PR DESCRIPTION
**Pull request by alexzhk**
Added oss-license.filename=PentahoHadoopShim_mapr510_OSS_Licenses.html in the build.property file.

### CODE REVIEW

**Comment by alexzhk** [comment]
Could you @dkincade @hudak please review my changes?

**Comment by dkincade** [comment]
@smaring Does this look correct to you?

**Comment by hudak** [comment]
Pull Request #384 was already merged into master. This PR should be rebased and the merge commit should be excluded.

**Comment by alexzhk** [comment]
@hudak I updated the pull request

**Comment by lucboudreau** [comment]
### Build Failed

:x: Something went wrong while validating this pull request.

#### Build Commands

```sh
ant -Dtestreports.dir=bin/reports/unit-test -f mapr510/build.xml clean-all resolve jacoco && ant -Dtestreports.dir=bin/reports/integration-test -f mapr510/build.xml jacoco-integration checkstyle
```

##### Stdout log
###### (last 100 lines)

```console
Config enriched: Set the slackbot url
Config enriched: If github SourceControlType and null StatusUpdateType, use github
Config enriched: If github SourceControlType and StatusUpdaterType and null ApiToken, use the one from SourceRetriever
Config enriched: If github SourceControlType and StatusUpdaterType and null Organization, use the one from SourceRetriever
Config enriched: If github SourceControlType and StatusUpdaterType and null Repository, use the one from SourceRetriever
Config enriched: If github SourceControlType and StatusUpdaterType and null PullRequest, use the one from SourceRetriever
Config enriched: CheckstyleAnalyzer is enabled by default
Retrieving source with org.pentaho.build.buddy.bundles.source.github.SlackbotGithubSourceRetriever@78190c9c
Git clone: [git, clone, --depth=10, --branch, master, https://[GITHUB TOKEN]@github.com/pentaho/pentaho-hadoop-shims.git, pentaho-hadoop-shims-base-386-0968f4d2-6f9f-4330-ac98-5a11695648f8]
Git fetch: [git, fetch, --depth=11, origin, pull/386/head:pullRequest]
Git merge: [git, merge, --no-edit, --no-ff, -X, theirs, pullRequest]
Cloning into 'pentaho-hadoop-shims-base-386-0968f4d2-6f9f-4330-ac98-5a11695648f8'...
Merge made by the 'recursive' strategy.
 mapr510/build.properties | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)
BuildToolDetector guessing ant project because build.xml exists in at the root or in the parent folder of a changed file: mapr510/build.properties
Config enriched: Default to Docker
Config enriched: Master branches default to java 8
Config enriched: Ant builds mount ivy repo
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Buildfile: mapr510/build.xml does not exist!
Build failed
rm: cannot remove '/home/buildguy/.ivy2/local': No such file or directory
no publish local to remove
```

#### Stderr log
###### (last 100 lines)

```console
From https://github.com/pentaho/pentaho-hadoop-shims
 * [new ref]         refs/pull/386/head -> pullRequest
java.lang.Exception: org.pentaho.build.buddy.bundles.orchestrator.OrchestratorImpl$BuildException: java.io.IOException: Base build returned with code 1
	at org.pentaho.build.buddy.bundles.orchestrator.OrchestratorImpl.orchestrate(OrchestratorImpl.java:373)
	at Proxy83ee0193_46e2_4e65_a5aa_1b7cb48ec62e.orchestrate(Unknown Source)
	at org.pentaho.build.buddy.bundles.rest.OrchestratorRestService$1.write(OrchestratorRestService.java:62)
	at org.apache.cxf.jaxrs.provider.BinaryDataProvider.writeTo(BinaryDataProvider.java:172)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.writeMessageBody(JAXRSUtils.java:1381)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.serializeMessage(JAXRSOutInterceptor.java:244)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.processResponse(JAXRSOutInterceptor.java:120)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleMessage(JAXRSOutInterceptor.java:83)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.interceptor.OutgoingChainInterceptor.handleMessage(OutgoingChainInterceptor.java:83)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:253)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:271)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.pentaho.build.buddy.bundles.orchestrator.OrchestratorImpl$BuildException: java.io.IOException: Base build returned with code 1
	at org.pentaho.build.buddy.bundles.orchestrator.OrchestratorImpl.doOrchestrate(OrchestratorImpl.java:518)
	at org.pentaho.build.buddy.bundles.orchestrator.OrchestratorImpl.orchestrate(OrchestratorImpl.java:355)
	... 41 more
Caused by: java.io.IOException: Base build returned with code 1
	... 43 more

```

**Pull request merged**
