### PR TITLE
[BAD-256] - backport  to the 5.3.0.2 branch

### PR DESCRIPTION
**Pull request by mtseu**
as soon as there is a bug in sqoop 4.5 cdh 5.3.0 version it's been decided to switch cdh53 shim to Cloidera 5.3.2 libraries

### CODE REVIEW

**Comment by mtseu** [comment]
@mattyb149 @brosander could you please review/merge?
@mbradbury2014 FYI

**Comment by brosander** [comment]
is this an sp branch?

**Comment by mtseu** [comment]
@brosander that's right.
If I understand this right the change is supposed to be included into the April SP.
So that it has to be merged over here. 
I think we could defer until PM confirms it's safe to merge.
@mbradbury2014 Could you please confirm?

**Comment by mtseu** [comment]
no need to merge to the SP release

**Pull request closed without merging**
