### PR TITLE
BACKLOG-14480 Create CDH 5.10 Shim module in Pentaho 7.0 CE, EE repositories

### PR DESCRIPTION
**Pull request by TatsianaKasiankova**
CE version of the new CDH 5.10 shim.

### CODE REVIEW

**Comment by TatsianaKasiankova** [comment]
@dkincade Hi, please review the PR.

**Comment by dkincade** [comment]
@vshalkova @duarteteixeira ... as an example, this is a PR to create a new version of the shim in the 7.0 repository. I would like to see @buildguy ( @lgrill-pentaho  or @smaring ) review this from the build properties / build inclusion point of view.

Also, the content is going to be pretty similar to the previous version, so someone else on the BDC team should be able to perform the review. If they can merger it, that would be good. If they can't then stating that they have reviewed it and it is good with a note to ask @duarteteixeira or someone else who does have rights to include it would be the next step.

**Comment by TatsianaKasiankova** [comment]
@alexzhk , @duarteteixeira please review and merge the PR.
https://github.com/pentaho/build-resources/pull/102 - merged by build team

**Comment by alexzhk** [comment]
@TatsianaKasiankova @duarteteixeira 
Looks good to me and can be merged.

**Pull request merged**
