### PR TITLE
[BUILD-FAIL] Added dependency for API module

### PR DESCRIPTION
**Pull request by stepanovdg**
This seems to fix compilation issue in EMR

### CODE REVIEW

**Comment by stepanovdg** [comment]
@mattyb149 Could you please merge this? Locally all is working with and without this. But these changes should help. (According to stacktrace )

**Comment by mattyb149** [comment]
Can we reproduce this? maybe a screencast video of it not working/working on EMR?

**Comment by stepanovdg** [comment]
Ci.pentaho.com  project pentaho-hadoop-shims is failing.
http://ci.pentaho.com/job/pentaho-hadoop-shims/256/changes
Locally all is ok. Seems these changes are required acording to stacktrace
in console output.
As I remember api is searched by ../api on curently working dir or somthing
like this - so when build is run from other working directory (as at
jenkins job now) javac is no able do find shims-api module.

2015-07-16 18:00 GMT+03:00 Matthew Burgess <notifications@github.com>:

**Comment by mattyb149** [comment]
Why is this shim different than the others? Seems we should fix the Ant build to have everyone resolve the API JAR instead of looking for it on the local file system.

**Comment by stepanovdg** [comment]
I don`t know really why looking on the local file system was added -seems
for easy local builds - its "historically" issue. We have already updated
some of the new shims (not sure seems they were failing before) to depend
on api-module. Also as I know almost everywhere already api-test module is
added.
 I can check  tomorrow all other shims(with disable local mode) - just was
trying to quickly fix build. As a result of letter with fail from buildguy.
Also it could  be fix only for the first issue((.

2015-07-16 22:25 GMT+03:00 Matthew Burgess <notifications@github.com>:

**Comment by mattyb149** [comment]
Ok I will merge to fix the build with your promise to look more closely at it after :)  Thanks!

**Pull request merged**
