### PR TITLE
[BAD-315] - Compile CDH54 shim for 5.4 release

### PR DESCRIPTION
**Pull request by mtseu**
@brosander @mattyb149

### CODE REVIEW

**Comment by andrei-viaryshka** [comment]
New PR based on this one is submitted for BAD-315:
https://github.com/pentaho/pentaho-hadoop-shims/pull/263.

**Comment by mattyb149** [comment]
I'm getting resolve errors for the following:

org.cloudera.logredactor#logredactor;1.0.2: not found
org.pentaho#pentaho-aggdesigner-algorithm;5.1.5-jhyde: not found

Are there COMP cases for these?

**Comment by andrei-viaryshka** [comment]
@mattyb149 https://github.com/pentaho/pentaho-hadoop-shims/pull/263 contains the fix for logredactor; as for org.pentaho#pentaho-aggdesigner-algorithm;5.1.5-jhyde - related case is COMP-1576 and according to @mbradbury2014 the jar will be available in the repo soon.

**Comment by mattyb149** [comment]
Closing in favor of #263

**Pull request closed without merging**
