### PR TITLE
[BACKLOG-7479]: Create and Compile HDP 2.4 SHIM

### PR DESCRIPTION
**Pull request by TatsianaKasiankova**

### CODE REVIEW

**Comment by TatsianaKasiankova** [comment]
@brosander, please review the PR.
CE version.

**Comment by brosander** [comment]
@TatsianaKasiankova have the new jars been through the component process?

**Comment by TatsianaKasiankova** [comment]
the component process is in progress (BACKLOG-7515).

**Comment by eliofreitas** [comment]
Rejected from automatic build ,authorized users only

**Pull request merged**
