### PR TITLE
[BAD-261] - PentahoTableInputFormat does not work on secured Hadoop cluster

### PR DESCRIPTION
**Pull request by stepanovdg**
* Added RequiredCredentialsToken which works at client side and allows to obtain required tokens w/out changes internally in shim`s abstraction layer.

### CODE REVIEW

**Comment by brosander** [comment]
@stepanovdg will the interface changes here break existing shims?

**Comment by stepanovdg** [comment]
There are two major changes. First is adding "RunningJob submit() " to Configuration interface. But all known implementations are ConfigurationProxy (in common code for old shims) and ConfigurationProxyV2 (in new common code fro the new shims). Another change HbaseConnection.obtainAuthTokenForJob( Configuration conf ) is implemented in common with empty methods and only in secured part added real functionality.
Existing shims need to be recompiled with new api.

**Comment by brosander** [comment]
@dkincade the changes make sense, this does require a full shim rebuild though

**Comment by stepanovdg** [comment]
@brosander  As branching is over - may be it`s time to merge this now?

**Comment by mbatchelor** [comment]
According to BAD-261, either #330 should be merged, or #332 and #333 should be merged. Since #330 was merged, this one needs to be closed.

**Pull request closed without merging**
