### PR TITLE
[SP-6626]- Backport of PPP-5312 - Vulnerable Component: hadoop-aws 3.3.0 - updating it to 3.4.0 (10.2 Suite)

### PR DESCRIPTION
**Pull request by rsleem**

### CODE REVIEW

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[👍 Frogbot scanned this pull request and did not find any new security issues.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 43m 56s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl shims/apache/driver
```
---
:ok_hand: All tests passed!
 
Tests run: **40**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-hadoop-shims/job/PR-1493/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by rmansoor** [comment]
Please do not process this PR. There is one more change we are missing. Raja is currently working on it

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[👍 Frogbot scanned this pull request and did not find any new security issues.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 44m 11s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl shims/apache/driver
```
---
:ok_hand: All tests passed!
 
Tests run: **40**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-hadoop-shims/job/PR-1493/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by rmansoor — APPROVED** [review]

**Comment by rmansoor** [comment]
The PR is ready to be merged now

**Pull request merged**
