### PR TITLE
[SP-6106] - Correct unit test failures related to log4j changes

### PR DESCRIPTION
**Pull request by andreramos89**
@renato-s 
@smmribeiro 
@bcostahitachivantara

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 1m 16s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl api,common/mapred
```
---
:ok_hand: All tests passed!
 
Tests run: **211**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-hadoop-shims-8/job/PR-1302/1/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 51s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl api,common/mapred
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 3s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl api,common/mapred
```
---
:ok_hand: All tests passed!
 
Tests run: **211**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-hadoop-shims-8/job/PR-1302/3/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Looks good.

**Pull request merged**
