### PR TITLE
[BAD-381] - Create and Compile HDP 2.3 SHIM

### PR DESCRIPTION
**Pull request by mtseu**

### CODE REVIEW

**Comment by mtseu** [comment]
@brosander @mattyb149 @dkincade could you please review/merge?

**Comment by mtseu** [comment]
EE part is: https://github.com/pentaho/pentaho-big-data-ee/pull/82

**Comment by mattyb149** [comment]
This shim has 19% code coverage, we need to discuss a general refactor and approach to get coverage up for all supported and existing shims.

**Comment by mattyb149** [comment]
Per a discussion with @dkincade, merging now with refactor/code coverage as a separate task

**Pull request merged**
