### PR TITLE
[BAD-394] - Misleading error message is shown if Cloudera Simba connection is not defined properly

### PR DESCRIPTION
**Pull request by stepanovdg**
* Added check for not trying to connect hive on impala URL
* Added tests

### CODE REVIEW

**Comment by stepanovdg** [comment]
@brosander Could you please take a look?

**Comment by brosander** [comment]
@stepanovdg are we expecting url prefixes other than jdbc:?  I'm worried this might cause issues if hive2 is somehow in a hostname (unlikely but possible).

**Comment by stepanovdg** [comment]
Mostly I think that in this case hostname or dbname should contain ":" symbol - which seems to be not allowed. "The Internet standards (Requests for Comments) for protocols mandate that component hostname labels may contain only the ASCII letters 'a' through 'z' (in a case-insensitive manner), the digits '0' through '9', and the hyphen ('-'). The original specification of hostnames in RFC 952, mandated that labels could not start with a digit or with a hyphen, and must not end with a hyphen. However, a subsequent specification (RFC 1123) permitted hostname labels to start with digits. No other symbols, punctuation characters, or white space are permitted."

But I understand you and can change regex to "jdbc:hive2:.*" and smth like this.

**Comment by brosander** [comment]
@stepanovdg ah, didn't notice the colon at the front, it's probably fine then

**Pull request merged**
