### PR TITLE
[PDI-13557] Added fix for NPE with missing variable space

### PR DESCRIPTION
**Pull request by mattyb149**

### CODE REVIEW

**Comment by kcruzada** [comment]
@mattyb149  are you going to pull this in?

**Comment by kcruzada** [comment]
@mattyb149 @mdamour1976 can you process this pull request?

**Comment by mattyb149** [comment]
@mdamour1976 Looks like you took a crack at this already (#236), this would support that with an extra path to create an empty set of variables

**Comment by kcruzada** [comment]
@mdamour1976 should this pull request be closed?

**Pull request merged**
