### PR TITLE
[BAD-277] - CDH54 shim support

### PR DESCRIPTION
**Pull request by mtseu**
the work separated into several commits:
[BAD-312] 
- support for new HBase 1.0 API, 
- some adjustments in abstraction layer to support very old HBase (like hadoop-20 shim), 
- add support to HBaseConnection API changes to all shims.

[BAD-281]
- CDH54 code base
- add the new shim to the entire build process

### CODE REVIEW

**Comment by mtseu** [comment]
@brosander @mattyb149 would you mind to review

**Comment by mtseu** [comment]
the next PR tp be merged is: https://github.com/pentaho/big-data-plugin/pull/412

**Comment by mtseu** [comment]
@lgrill-pentaho FYI (see http://jira.pentaho.com/browse/BAD-286)

**Comment by mattyb149** [comment]
I'm getting resolve errors during compile:

org.cloudera.logredactor#logredactor;1.0.2: not found
org.pentaho#pentaho-aggdesigner-algorithm;5.1.5-jhyde: not found

Were these added via COMP cases? If so they should be available via our Nexus repo, but they don't appear to be.

**Comment by mattyb149** [comment]
Closing in favor of #264

**Pull request closed without merging**
