### PR TITLE
[TEST] - pentaho-hadoop-shims continuous problem

### PR DESCRIPTION
**Pull request by kolinus**
What was done:
1) fixed continious target

### CODE REVIEW

**Comment by kolinus** [comment]
@mattyb149  Matt, we do not see 5.3  jobs on CI.so this is a backport of https://github.com/pentaho/pentaho-hadoop-shims/pull/217/files in case we need it. As I said we do not see the jobs so can't understan if it fails and if so is the reason same as for MASTER or not.

**Comment by mattyb149** [comment]
There are no CI jobs for 5.3

**Comment by mattyb149** [comment]
The kolinus:BUILD-ISSUE branch needs to be rebased against the latest pentaho:5.3

**Comment by mbradbury2014** [comment]
Last SP for 5.3.  Not going to add this to the code line

**Pull request closed without merging**
