### PR TITLE
[REFACTOR] - Extract to common part. 

### PR DESCRIPTION
**Pull request by stepanovdg**
Mostly for test purposes and do not having code duplicating.

### CODE REVIEW

**Comment by stepanovdg** [comment]
@brosander Could you please take a look?

**Comment by stepanovdg** [comment]
http://ci.pentaho.com/job/pentaho-hadoop-shims-stepanovdg-fork/ - CI build and test results

**Comment by brosander** [comment]
@stepanovdg very happy about this work, manual review of the diff probably won't be productive though
1. Have we regression tested these changes?
2. Have we verified that the artifacts produced have the same 3rd party components?
3. Are we good on checkstyles?

/cc @dkincade

**Comment by stepanovdg** [comment]
1. All tests that was before successfully passed. Mostly as this refactoring was made for easy test coverage - were not written tests still for this refactoring. I have manually tested 2 shims (one some cdh unsecured and mar410 secured) to check there work on cluster. @IChekan is also checking hdp23 secured (almost done except of yarn (long time staging)).

2. Also was checked some randomly chosen shims to check. There were no changes on distributive dependencies, still used previous ivy.xml files. Some test dependencies were added to mapr shims (they didn`t contain tests before so even junit and mockito was missing).

3 I tried to follow check-style and have configured check in my ide - but mostly this check is not relevant with the check-style check from command line. But at that moment ant checkstyle was not working. So that`s why will update with check-style as soon as it will be fixed.

**Comment by stepanovdg** [comment]
Ihar has succeeded in checking hdp23 secured shim.

**Pull request merged**
