### PR TITLE
[BACKLOG-8747]: Create and Compile EMR 4.6 SHIM against Pentaho 7.0 (master)

### PR DESCRIPTION
**Pull request by TatsianaKasiankova**
The new EMR 4.6 shim reworked according to the new upcoming dependency management changes:
1)All third party and test dependencies use transitive="false";
2)Pentaho Dependencies uses the property keys from the global version.properties for their versions;

### CODE REVIEW

**Comment by TatsianaKasiankova** [comment]
@dkincade Hi, please review the PR.
We still have:
head: [ivy:resolve]         ::::::::::::::::::::::::::::::::::::::::::::::
head: [ivy:resolve]         ::          UNRESOLVED DEPENDENCIES         ::
head: [ivy:resolve]         ::::::::::::::::::::::::::::::::::::::::::::::
head: [ivy:resolve]         :: org.apache.hive#hive-jdbc;1.0.0: not found
head: [ivy:resolve]         :: org.apache.hive#hive-exec;1.0.0: not found
head: [ivy:resolve]         :: org.apache.hive#hive-service;1.0.0: not found
head: [ivy:resolve]         :: org.apache.hive#hive-metastore;1.0.0: not found
head: [ivy:resolve]         :: org.apache.oozie#oozie-core;4.2.0: not found
head: [ivy:resolve]         :: org.apache.oozie#oozie-client;4.2.0: not found
head: [ivy:resolve]         ::::::::::::::::::::::::::::::::::::::::::::::

**Comment by lucboudreau** [comment]
```
Fri Jun 24 14:03:20 EDT 2016 - stdout - head: [ivy:resolve] 		::::::::::::::::::::::::::::::::::::::::::::::
Fri Jun 24 14:03:20 EDT 2016 - stdout - head: [ivy:resolve] 		::          UNRESOLVED DEPENDENCIES         ::
Fri Jun 24 14:03:20 EDT 2016 - stdout - head: [ivy:resolve] 		::::::::::::::::::::::::::::::::::::::::::::::
Fri Jun 24 14:03:20 EDT 2016 - stdout - head: [ivy:resolve] 		:: org.apache.hive#hive-jdbc;1.0.0: not found
Fri Jun 24 14:03:20 EDT 2016 - stdout - head: [ivy:resolve] 		:: org.apache.hive#hive-exec;1.0.0: not found
Fri Jun 24 14:03:20 EDT 2016 - stdout - head: [ivy:resolve] 		:: org.apache.hive#hive-service;1.0.0: not found
Fri Jun 24 14:03:20 EDT 2016 - stdout - head: [ivy:resolve] 		:: org.apache.hive#hive-metastore;1.0.0: not found
Fri Jun 24 14:03:20 EDT 2016 - stdout - head: [ivy:resolve] 		:: org.apache.oozie#oozie-core;4.2.0: not found
Fri Jun 24 14:03:20 EDT 2016 - stdout - head: [ivy:resolve] 		:: org.apache.oozie#oozie-client;4.2.0: not found
Fri Jun 24 14:03:20 EDT 2016 - stdout - head: [ivy:resolve] 		::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by lucboudreau** [comment]
Wingman reported the error for the base build above, but there are also missing dependencies in the head build. The build team is looking into the missing dependencies, but it will not resolve the error on the base build.

To fix this problem, I need to know what ant command to use for the shim project. Can someone tell me if this command is ok with the shims?

```
ant -Dpentaho.resolve.repo=http://ivy-nexus.pentaho.org/content/groups/approved -Dtestreports.dir=bin/reports/unit-test -f build.xml clean-all resolve jacoco \
ant -Dpentaho.resolve.repo=http://ivy-nexus.pentaho.org/content/groups/approved -Dtestreports.dir=bin/reports/integration-test -f build.xml jacoco-integration checkstyle publish-local
```

**Comment by TatsianaKasiankova** [comment]
@lucboudreau Hi, Luc
On http://devci.pentaho.com/ the followings ant targets are used: clean-all resolve dist jacoco publish (e.g. see http://devci.pentaho.com/job/master-snapshot/job/big-data-hadoop-shims/620/consoleFull);
The test job on http://ci.pentaho.com uses: build-all continuous-sonar (see e.g. http://ci.pentaho.com/job/pentaho-hadoop-shims-stepanovdg-fork1/152/consoleFull);
Locally I usually build via the targets:
ant clean-all resolve

**Comment by TatsianaKasiankova** [comment]
@dkincade , @lucboudreau Hi, Could you please take a look. It is still failed and on jacoco targets for EMR41 shim.
It seems that there is a problem with any wingman env settings.

**Comment by lucboudreau** [comment]
@TatsianaKasiankova I'm looking into it, but for the moment, please validate manually and merge when ready.

**Comment by VasilinaTerehova** [comment]
As Tatsiana is on vacation now, I sent pull request with her changes and my updates - fixes, and sqoop version update from my repo. The new pull request is at https://github.com/pentaho/pentaho-hadoop-shims/pull/371

**Comment by TatsianaKasiankova** [comment]
Closed because these changes+fixes for checkstyle violations and etc. have been merged in the https://github.com/pentaho/pentaho-hadoop-shims/pull/366

**Pull request closed without merging**
