### PR TITLE
[BACKLOG-10556]: Fix/Add/Rework unit tests in big-data-plugin\kettle-…

### PR DESCRIPTION
**Pull request by TatsianaKasiankova**
…plugins after deletion hadoop-20 shim

Moved and refactored unit tests from org.pentaho.hadoop.mapreduce.test.PentahoMapReduceIT to pentaho-hadoop-shims\common
Because they test methods in GenericTransCombiner, GenericTransReduce and PentahoMapRunnable and should be placed in the appropriate project - pentaho-hadoop-shims\common
Added target to run integration tests for pentaho-hadoop-shims\common\test-src\

### CODE REVIEW

**Comment by TatsianaKasiankova** [comment]
@dkincade Hi, I've deleted unnecessary information in the test  transformations.
Also added one more IT test. Verified locally.

**Comment by dkincade** [comment]
I want to wait for WingMan to chew on this one first ... but a visual inspection looks good.

**Comment by TatsianaKasiankova** [comment]
@dkincade Wingman rules exclude changes in pentaho-hadoop-shims\common to check.

**Comment by dkincade** [comment]
Let's watch it in devci

**Pull request merged**
