### PR TITLE
[BAD-257] - MapR401: PDI fails to load when mapr401 shim is set active

### PR DESCRIPTION
**Pull request by andrei-viaryshka**
Updated build.xml and ivy.xml.

### CODE REVIEW

**Comment by andrei-viaryshka** [comment]
@mattyb149 @brosander Could you please review?

**Comment by brosander** [comment]
@andrei-viaryshka Shouldn't we be using our own org, artifact id for a modified hive driver?

**Comment by andrei-viaryshka** [comment]
I'm not sure about this. We are just removing extra jars from lib folder for now.
Do we need to do some additional changes here?

**Comment by andrei-viaryshka** [comment]
Updated PR: added test dependencies.

**Pull request merged**
