### PR TITLE
[BACKLOG-23080] - Updated project structure to support multishim

### PR DESCRIPTION
**Pull request by wseyler**

### CODE REVIEW

**Comment by wseyler** [comment]
[BACKLOG-23569] - Change of Story

**Comment by lucboudreau** [comment]
^^ I launched Wingman for fun because my own machine was giving me troubles today.

**Comment by wseyler** [comment]
Not sure what's going on here.

**Comment by lucboudreau** [comment]
It couldn't validate your maven changes. Says there are some properties missing. 

```
[ERROR] 'dependencies.dependency.version' for com.yammer.metrics:metrics-core:jar is missing. @ 
[ERROR] 'dependencies.dependency.version' for pentaho:pentaho-hdfs-vfs:jar is missing. @ 
```

Could be a wingman thing though. I mean, give it a second look but just validate locally if you need. It'd be surprised if Wingman can even build this, since it adds a new module.

**Pull request closed without merging**
