### PR TITLE
[PPP-5200] Vulnerable Component: Avro (Hadoop Vulnerable Component Only)

### PR DESCRIPTION
**Pull request by nawaz34-hitachivantara**

### CODE REVIEW

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[👍 Frogbot scanned this pull request and did not find any new security issues.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 31m 45s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl shims/emr700/driver
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[👍 Frogbot scanned this pull request and did not find any new security issues.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 33m 19s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
shims/apache/driver,shims/apache/kar,shims/dataproc1421/driver,shims/dataproc1421/kar
```
---
:ok_hand: All tests passed!
 
Tests run: **40**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-hadoop-shims/job/PR-1502/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by nawaz34-hitachivantara** [comment]
Changes of this PR are already addressed in https://github.com/pentaho/pentaho-hadoop-shims/pull/1516. Hence closing this.

**Pull request closed without merging**
