### PR TITLE
[BACKLOG-14449]-Create and Dev Validate CDH 5.10 Shim against Pentaho 7.1 (Master)

### PR DESCRIPTION
**Pull request by alexzhk**
Added cdh510 ce version of the shim.

### CODE REVIEW

**Comment by alexzhk** [comment]
@duarteteixeira  @TatsianaKasiankova  @VasilinaTerehova 

As Tatsiana has an issue on her local machine when running script to convert cdh510 shim to maven, I sent this pull request and Tatsiana now is dealing with dev testing of cdh510 Shim.

**Comment by alexzhk** [comment]
Could you @VasilinaTerehova please review this pull request?

**Comment by TatsianaKasiankova** [comment]
The properties for the new shim have been added: https://github.com/pentaho/build-resources/pull/113

**Comment by VasilinaTerehova** [comment]
@duarteteixeira @alexzhk @TatsianaKasiankova the PR looks ok for me

**Pull request merged**
