### PR TITLE
[SP-6610] Backport of PPP-5166 - Use of Vulnerable Component: Components/jackson-databind 2.14.2 (Non OSGi upgrade)

### PR DESCRIPTION
**Pull request by rmansoor**

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 47s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model
[FATAL] Non-parseable POM /build/wingman/workspace/maintenance/wingman/builds/pentaho.pentaho-hadoop-shims.PR-1483/shims/apache/driver/pom.xml: Duplicated tag: 'exclusions' (position: START_TAG seen ...</exclusions>\n      <exclusions>... @197:19)  @ line 197, column 19
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 33s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model
[FATAL] Non-parseable POM /build/wingman/workspace/maintenance/wingman/builds/pentaho.pentaho-hadoop-shims.PR-1483/shims/apache/driver/pom.xml: Duplicated tag: 'exclusions' (position: START_TAG seen ...</exclusions>\n      <exclusions>... @197:19)  @ line 197, column 19
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 38s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model
[FATAL] Non-parseable POM /build/wingman/workspace/maintenance/wingman/builds/pentaho.pentaho-hadoop-shims.PR-1483/shims/apache/driver/pom.xml: Duplicated tag: 'exclusions' (position: START_TAG seen ...</exclusions>\n      <exclusions>... @197:19)  @ line 197, column 19
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 48s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 37s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model
[FATAL] Non-parseable POM /build/wingman/workspace/maintenance/wingman/builds/pentaho.pentaho-hadoop-shims.PR-1483/shims/apache/driver/pom.xml: Duplicated tag: 'exclusions' (position: START_TAG seen ...</exclusions>\n      <exclusions>... @197:19)  @ line 197, column 19
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 30s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model
[FATAL] Non-parseable POM /build/wingman/workspace/maintenance/wingman/builds/pentaho.pentaho-hadoop-shims.PR-1483/shims/apache/driver/pom.xml: Duplicated tag: 'exclusions' (position: START_TAG seen ...</exclusions>\n      <exclusions>... @197:19)  @ line 197, column 19
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 34s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model
[FATAL] Non-parseable POM /build/wingman/workspace/maintenance/wingman/builds/pentaho.pentaho-hadoop-shims.PR-1483/shims/apache/driver/pom.xml: Duplicated tag: 'exclusions' (position: START_TAG seen ...</exclusions>\n      <exclusions>... @197:19)  @ line 197, column 19
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 49s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by smmribeiro** [comment]
The build is failing due to an error on '/shims/apache/driver/pom.xml' (check lines 191/202: there should only exist an "exclusions" group and there are two).
I couldn't make changes on this PR branch, so I created a new one with an extra commit with the fix: [pentaho-hadoop-shims#1484](https://github.com/pentaho/pentaho-hadoop-shims/pull/1484).
Closing this PR in favour of the latter.

**Pull request closed without merging**
