### PR TITLE
[BACKLOG-5188] -  [REGRESSION]: EMR34 shim: Unable to load shim error.

### PR DESCRIPTION
**Pull request by stepanovdg**
* Added missed pentaho-vfs jar to dist
* Removed unnecessary for runtime shims-api jar

### CODE REVIEW

**Comment by stepanovdg** [comment]
@brosander Could you please take a look?

**Comment by brosander** [comment]
@stepanovdg are provided dependencies getting into the dist?  shouldn't pentaho-hdfs-vfs be default and the shim api be provided?

**Comment by stepanovdg** [comment]
Seems that is why was the problem. Also thought before. I tried the fix and call ant dist on shim - to be really sure. In case of this configuration - we are resolving API for compile and are not including it to the dist. And for pentaho-hdfs-vfs  - need to be included to dist.

**Comment by dkincade** [comment]
@brosander is this safe to merge or is there more update needed?

**Comment by brosander** [comment]
@stepanovdg the change has the desired effect, provided dependencies should be used for those that are needed for compile but not distribution in the future if possible.

**Pull request merged**
